color0 #291514
color1 #842621
color2 #e46e67
color3 #5cc8d6
color4 #d0d65c
color5 #ec9893
color6 #96dfe9
color7 #f3f2f2
color8 #756160
color9 #842621
color10 #e46e67
color11 #5cc8d6
color12 #d0d65c
color13 #ec9893
color14 #96dfe9
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291514
background            #291514
foreground            #f3f2f2
selection_foreground  #b6afaf
selection_background  #371c1b
active_border_color   #e46e67
inactive_border_color #371c1b
url_color             #e46e67

active_tab_foreground   #251918
active_tab_background   #e46e67
inactive_tab_foreground #b6afaf
inactive_tab_background #371c1b
cursor_trail_color      #b6afaf
